### ISSUE TITLE
【デザインリニューアル】一般モードのProject v2を公開

### ISSUE THREAD

**Issue by SofPyon** [SofPyon/inaka-portal#249]
## 背景

一般モードの Project v2 化は完了したので、公開する。

## 実装内容

Project v2 の一般モードをデフォルトにする

- [x] お問い合わせ・設定ページなどで、サイドドロワーやボトムナビを、他の Project v2 に揃える
- [x] メール認証完了後の画面の「ダッシュボードへ」というボタンを「ホームへ」に変える
- [x] 「参加登録しましょう」ボタンを非表示にする（まだ参加登録機能の実装が終わっていないので）
- [x] home__v2 と forms__v2 から __v2 をとる
- [x] url('/') を route('home') に変える
- [x] Project v2 に置き換えられた CodeIgniter のコード＆Bootstrap 4 製の Blade を削除
- [x] スタッフモードへの導線を追加
- [x] 現状の login?new=1 を home にする
- [x] home は `/` (Root URL) にする
- [x] 「ログイン画面が新しくなりました」は削除する

とか？ 

## 検討事項

- 公開日は？
    - パンフ申請の受付終了日以降
    - デザインに大きな変更はないはずだが、告知からある程度余裕を持ってリリースする

**Comment by SofPyon** [comment]
## TODO
- [x] なぜかスタッフモードの認証が必ず失敗するようになってしまったので、原因調査
- [ ] 全体的にかなりバグありそう？
